# Use an official Python runtime as the base image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the script and install dependencies
COPY listener.py /app/
RUN python3 -m pip install -U discord.py-self

# Run the script when the container launches
CMD ["python", "listener.py"]
